---

- name: pull from remote sshkey vault
  git: repo="{{ remote_sshkey_vault_repo }}" dest="{{ local_sshkey_vault_repo }}" update=yes recursive=no
  become: no
  delegate_to: localhost
  run_once: true
  when: remote_sshkey_vault_repo is defined

- name: include access config
  include_vars: "{{ local_sshkey_vault_repo }}/host_confs/{{inventory_hostname}}.yml"

- name: detect ssh ecdsa implementation
  set_fact: ssh_algs="{{ ssh_algs  + ['ecdsa']}}"
  when: ansible_ssh_host_key_ecdsa_public is defined

- name: detect ssh ed25519 implementation
  set_fact: ssh_algs="{{ ssh_algs  + ['ed25519']}}"
  when: ansible_ssh_host_key_ed25519_public is defined

- name: assemble and deploy authorized_keys
  authorized_key: user="{{ item.user }}" key="{% for alg in item.algs %}{% if alg.name in ssh_algs %}{{ alg.authorized | join('\n') + '\n'}}{% endif %}{% endfor %}" exclusive=yes
  with_items:
        - "{{ users }}"

